<?php

namespace Database\Seeders;

use App\Models\Color;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ColorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['color_name' => 'red', 'color_code' => '#FF0000'],
            ['color_name' => 'green', 'color_code' => '#00FF00'],
            ['color_name' => 'blue', 'color_code' => '#0000FF'],
            ['color_name' => 'yellow', 'color_code' => '#FFFF00'],
            ['color_name' => 'purple', 'color_code' => '#800080'],
            ['color_name' => 'pink', 'color_code' => '#FFC0CB'],
            ['color_name' => 'orange', 'color_code' => '#FFA500'],
            ['color_name' => 'brown', 'color_code' => '#A52A2A'],
            ['color_name' => 'cyan', 'color_code' => '#00FFFF'],
            ['color_name' => 'magenta', 'color_code' => '#FF00FF'],
            ['color_name' => 'lavender', 'color_code' => '#E6E6FA'],
            ['color_name' => 'teal', 'color_code' => '#008080'],
            ['color_name' => 'turquoise', 'color_code' => '#40E0D0'],
            ['color_name' => 'gold', 'color_code' => '#FFD700'],
            ['color_name' => 'silver', 'color_code' => '#C0C0C0'],
            ['color_name' => 'gray', 'color_code' => '#808080'],
            ['color_name' => 'black', 'color_code' => '#000000'],
            ['color_name' => 'white', 'color_code' => '#FFFFFF'],
            ['color_name' => 'beige', 'color_code' => '#F5F5DC'],
            ['color_name' => 'maroon', 'color_code' => '#800000'],
            ['color_name' => 'navy', 'color_code' => '#000080'],
            ['color_name' => 'olive', 'color_code' => '#808000'],
            ['color_name' => 'aqua', 'color_code' => '#00FFFF'],
            ['color_name' => 'lime', 'color_code' => '#00FF00'],
            ['color_name' => 'fuchsia', 'color_code' => '#FF00FF'],
            ['color_name' => 'indigo', 'color_code' => '#4B0082'],
            ['color_name' => 'crimson', 'color_code' => '#DC143C'],
            ['color_name' => 'violet', 'color_code' => '#8A2BE2'],
            ['color_name' => 'limegreen', 'color_code' => '#32CD32'],
            ['color_name' => 'peru', 'color_code' => '#CD853F'],
            ['color_name' => 'slategray', 'color_code' => '#708090'],
            ['color_name' => 'salmon', 'color_code' => '#FA8072'],
            ['color_name' => 'skyblue', 'color_code' => '#87CEEB'],
            ['color_name' => 'chartreuse', 'color_code' => '#7FFF00'],
            ['color_name' => 'mint', 'color_code' => '#98FB98'],
            ['color_name' => 'lemonchiffon', 'color_code' => '#FFFACD'],
            ['color_name' => 'tan', 'color_code' => '#D2B48C'],
            ['color_name' => 'coral', 'color_code' => '#FF6F61'],
            ['color_name' => 'turquoiseblue', 'color_code' => '#00C5CD'],
            ['color_name' => 'khaki', 'color_code' => '#F0E68C'],
            ['color_name' => 'orchid', 'color_code' => '#DA70D6'],
            ['color_name' => 'royalblue', 'color_code' => '#4169E1'],
            ['color_name' => 'tomato', 'color_code' => '#FF6347'],
            ['color_name' => 'slateblue', 'color_code' => '#6A5ACD'],
            ['color_name' => 'moccasin', 'color_code' => '#FFE4B5'],
            ['color_name' => 'steelblue', 'color_code' => '#4682B4'],
            ['color_name' => 'mediumaquamarine', 'color_code' => '#66CDAA'],
            ['color_name' => 'peachpuff', 'color_code' => '#FFDAB9'],
            ['color_name' => 'sienna', 'color_code' => '#A0522D'],
            ['color_name' => 'darkolivegreen', 'color_code' => '#556B2F'],
            ['color_name' => 'hotpink', 'color_code' => '#FF69B4'],
            ['color_name' => 'cornflowerblue', 'color_code' => '#6495ED'],
            ['color_name' => 'burlywood', 'color_code' => '#DEB887'],
            ['color_name' => 'springgreen', 'color_code' => '#00FF7F'],
            ['color_name' => 'thistle', 'color_code' => '#D8BFD8'],
            ['color_name' => 'deepskyblue', 'color_code' => '#00BFFF'],
            ['color_name' => 'rosybrown', 'color_code' => '#BC8F8F'],
            ['color_name' => 'aquamarine', 'color_code' => '#7FFFD4'],
            ['color_name' => 'lightcoral', 'color_code' => '#F08080'],
            ['color_name' => 'palegoldenrod', 'color_code' => '#EEE8AA'],
            ['color_name' => 'darkslategray', 'color_code' => '#2F4F4F'],
            ['color_name' => 'lightskyblue', 'color_code' => '#87CEFA'],
            ['color_name' => 'indianred', 'color_code' => '#CD5C5C'],
            ['color_name' => 'darkturquoise', 'color_code' => '#00CED1'],
            ['color_name' => 'chocolate', 'color_code' => '#D2691E'],
            ['color_name' => 'yellowgreen', 'color_code' => '#9ACD32'],
            ['color_name' => 'plum', 'color_code' => '#DDA0DD'],
            ['color_name' => 'darkviolet', 'color_code' => '#9400D3'],
            ['color_name' => 'mediumvioletred', 'color_code' => '#C71585'],
            ['color_name' => 'saddlebrown', 'color_code' => '#8B4513'],
            ['color_name' => 'darkorchid', 'color_code' => '#9932CC'],
            ['color_name' => 'lightsalmon', 'color_code' => '#FFA07A'],
            ['color_name' => 'forestgreen', 'color_code' => '#228B22'],
            ['color_name' => 'mediumpurple', 'color_code' => '#9370DB'],
            ['color_name' => 'darkorange', 'color_code' => '#FF8C00'],
            ['color_name' => 'lightgreen', 'color_code' => '#90EE90'],
            ['color_name' => 'powderblue', 'color_code' => '#B0E0E6'],
            ['color_name' => 'crimson', 'color_code' => '#DC143C'],
            ['color_name' => 'gainsboro', 'color_code' => '#DCDCDC'],
            ['color_name' => 'deeppink', 'color_code' => '#FF1493'],
            ['color_name' => 'sandybrown', 'color_code' => '#F4A460'],
            ['color_name' => 'darkkhaki', 'color_code' => '#BDB76B'],
            ['color_name' => 'lightseagreen', 'color_code' => '#20B2AA'],
            ['color_name' => 'papayawhip', 'color_code' => '#FFEFD5'],
            ['color_name' => 'lightsteelblue', 'color_code' => '#B0C4DE'],
            ['color_name' => 'maroon', 'color_code' => '#800000'],
            ['color_name' => 'darkgoldenrod', 'color_code' => '#B8860B'],
            ['color_name' => 'mediumturquoise', 'color_code' => '#48D1CC'],
            ['color_name' => 'lavenderblush', 'color_code' => '#FFF0F5'],
            ['color_name' => 'mediumorchid', 'color_code' => '#BA55D3'],
            ['color_name' => 'cadetblue', 'color_code' => '#5F9EA0'],
            ['color_name' => 'lightpink', 'color_code' => '#FFB6C1'],
            ['color_name' => 'seagreen', 'color_code' => '#2E8B57'],
            ['color_name' => 'rosybrown', 'color_code' => '#BC8F8F'],
            ['color_name' => 'skyblue', 'color_code' => '#87CEEB'],
            ['color_name' => 'lemonchiffon', 'color_code' => '#FFFACD'],
            ['color_name' => 'chocolate', 'color_code' => '#D2691E'],
            ['color_name' => 'lightskyblue', 'color_code' => '#87CEFA'],
            ['color_name' => 'lightcyan', 'color_code' => '#E0FFFF'],
            ['color_name' => 'darksalmon', 'color_code' => '#E9967A'],
            ['color_name' => 'mediumslateblue', 'color_code' => '#7B68EE'],
            ['color_name' => 'olivedrab', 'color_code' => '#6B8E23'],
            ['color_name' => 'royalblue', 'color_code' => '#4169E1'],
            ['color_name' => 'firebrick', 'color_code' => '#B22222'],
            ['color_name' => 'lightgray', 'color_code' => '#D3D3D3'],
            ['color_name' => 'palevioletred', 'color_code' => '#DB7093'],
            ['color_name' => 'limegreen', 'color_code' => '#32CD32'],
            ['color_name' => 'darkseagreen', 'color_code' => '#8FBC8F'],
            ['color_name' => 'multi color', 'color_code' => '#8FBC8F']
        ];

        Color::insert($data);
    }
}
